import { Inter } from "next/font/google";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="valentine" className="scroll-smooth focus:scroll-auto">
      <body className={inter.className}>
        <navbar>
          <div className="drawer">
            <input id="my-drawer-3" type="checkbox" className="drawer-toggle" /> 
            <div className="drawer-content flex flex-col">
              {/* Navbar */}
              <div className="w-full navbar bg-pink-100 text-indigo-600 fixed top-0 z-50">
                <div className="flex-none lg:hidden">
                  <label htmlFor="my-drawer-3" aria-label="open sidebar" className="btn btn-square btn-ghost">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-6 h-6 stroke-current"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                  </label>
                </div> 
                <div className="flex-1 px-2 mx-2 font-bold text-xl"><a href="/#home">Pet Care App</a></div>
                <div className="flex-none hidden lg:block">
                  <ul className="menu menu-horizontal px-1">
                    {/* Navbar menu content here */}
                    <li><a href="/#home">Home</a></li>
                    <li><a href="/#service-type">Service</a></li>
                    <li><a href="/branch">Branch</a></li>
                    <li><a href="/#review">Review</a></li>
                    <li><a href="/#contact">Contact</a></li>
                    <li><a href="/#faq">FAQ</a></li>
                    <li>
                      <details>
                        <summary>
                          Dashboard
                        </summary>
                        <ul className="p-2 bg-amber-50 rounded-t-none">
                          <li><a href="/dashboard/my-orders">My Orders</a></li>
                          <li><a href="/dashboard/branch">Branch</a></li>
                          <li><a href="/dashboard/users">Users</a></li>
                          <li><a href="/dashboard/orders">Orders</a></li>
                        </ul>
                      </details>
                    </li>
                    <li>
                      <details>
                        <summary>
                          Account
                        </summary>
                        <ul className="p-2 bg-amber-50 rounded-t-none">
                          <li><a href="/register">Register</a></li>
                          <li><a href="/dashboard/profile">Profile</a></li>
                          <li><a href="/login">Login</a></li>
                          <li><a href="/logout">Logout</a></li>
                        </ul>
                      </details>
                    </li>
                  </ul>
                </div>
              </div>
              {/* Page content here */}
              <div className="mt-14">{children}</div>
            </div>
            <div className="drawer-side">
              <label htmlFor="my-drawer-3" aria-label="close sidebar" className="drawer-overlay"></label> 
              <ul className="menu p-4 w-80 min-h-full mt-12 bg-pink-100 text-indigo-600">
              <li>
                <details>
                  <summary>
                    Dashboard
                  </summary>
                  <ul className="p-2 bg-amber-50 rounded-t-none">
                    <li><a href="/dashboard/my-orders">My Orders</a></li>
                    <li><a href="/dashboard/branch">Branch</a></li>
                    <li><a href="/dashboard/users">Users</a></li>
                    <li><a href="/dashboard/orders">Orders</a></li>
                  </ul>
                </details>
              </li>
              <li>
                  <details>
                    <summary>
                      Account
                    </summary>
                    <ul className="p-2 bg-amber-50 rounded-t-none">
                      <li><a href="/register">Register</a></li>
                      <li><a href="/dashboard/profile">Profile</a></li>
                      <li><a href="/login">Login</a></li>
                      <li><a href="/logout">Logout</a></li>
                    </ul>
                  </details>
                </li>
                <li><a href="/#home">Home</a></li>
                <li><a href="/#service-type">Service</a></li>
                <li><a href="/branch">Branch</a></li>
                <li><a href="/#review">Review</a></li>
                <li><a href="/#contact">Contact</a></li>
                <li><a href="/#faq">FAQ</a></li>
              </ul>
            </div>
          </div>
        </navbar>
        <footer className="footer p-10 bg-neutral text-neutral-content">
          <aside>
            <svg width="50" height="50" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fillRule="evenodd" clipRule="evenodd" className="fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg>
            <p>ACME Industries Ltd.<br/>Providing reliable tech since 1992</p>
          </aside> 
          <nav>
            <section id="contact">
              <h6 className="footer-title">Contact Us</h6>
              <ul>
                <li>
                  Email : example.com
                </li>
                <li>
                  Phone : +6293019209201
                </li>
              </ul>
            </section>
          </nav>
        </footer>
      </body>
    </html>
  );
}
